name: Screenshots

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.4]

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: pdo_sqlite

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress

      - name: Setup database
        run: |
          cd demo && ./build.sh

      - name: Execute Unit Tests
        run: vendor/bin/phpunit --testsuite=Browser

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: debugbar-screenshots
          path: tests/screenshots
